repos:
- repo: local
  hooks:
  - id: black
    name: Format with Black
    entry: poetry run black
    language: system
    types: [python]
    exclude: ^.*\b(migrations)\b.*$
    args: [--fast]

  - id: flake8
    name: Check with Flake8
    entry: poetry run flake8
    language: system
    pass_filenames: false
    types: [python]
    args: [--count, "--max-line-length=120", "--exclude=migrations"]
