repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: check-toml
  - id: end-of-file-fixer
    exclude: "migrations"

- repo: https://github.com/asottile/add-trailing-comma
  rev: v2.1.0
  hooks:
  - id: add-trailing-comma

- repo: local
  hooks:
  - id: black
    name: Format with Black
    entry: poetry run black
    language: system
    types: [python]
    args: [--fast, "--exclude=migrations"]

  - id: flake8
    name: Check with Flake8
    entry: poetry run flake8
    language: system
    pass_filenames: false
    types: [python]
    args: [--count, "--max-line-length=120", "--exclude=migrations"]
