version: "3.9"

services:

  app:
    build: .
    container_name: app
    restart: always
    ports:
      - "8000:8000"
    command: bash -c "./wait-for-rabbitmq.sh rabbitmq && python api/main.py"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  producer:
    build: .
    container_name: producer
    restart: always
    ports:
      - "8080:8080"
    command: bash -c "./wait-for-rabbitmq.sh rabbitmq && python data_loader/data_loader.py"
    env_file:
      - .env
    depends_on:
      - db
      - rabbitmq

  db:
    image: postgres:15.1-alpine
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    env_file:
    - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
